"""add pet_count to cat model

Revision ID: f6c55d7bb67c
Revises: a0631ee7c6c3
Create Date: 2023-06-14 14:06:07.725155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c55d7bb67c'
down_revision = 'a0631ee7c6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('pet_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'pet_count')
    # ### end Alembic commands ###
